### PR TITLE
added my name and what I consider skills, or whatever, that I'm comfo…

### PR DESCRIPTION
**Pull request by stephen-grzenia**
…rtable with. And it seems the title for pull requests has a character limit. Interesting

### CODE REVIEW

**Comment by EBaxter1** [comment]
Seems fine to me

**Comment by AFoggs** [comment]
All good~

**Comment by Ore1** [comment]
Look fine

**Comment by stephen-grzenia** [comment]
Didn't feel like typing a new email. I'm fixing the post on basecamp cause
stolley got a bug up his butt. Should be done soon

On Mar 28, 2017 2:09 PM, "Oreoluwa Olotu" <notifications@github.com> wrote:

Merged #5 <https://github.com/scarletfoxes/new-portal/pull/5>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/scarletfoxes/new-portal/pull/5#event-1019168712>, or mute
the thread

**Pull request merged**
