### PR TITLE
Did stuff stuff

### PR DESCRIPTION
**Pull request by EBaxter1**
Tried to fix hamburger, Steve is that what you had wanted to happen? 
Added logo 
Changed some of the nav link that I thought we didn't need

### CODE REVIEW

**Comment by Ore1** [comment]
It looks fine to me but the px units need to be changed to em.

**Comment by AFoggs** [comment]
What Ore said, but otherwise good.

**Comment by EBaxter1** [comment]
I mean i didn't convert because I thought you were still working on that

**Comment by stephen-grzenia** [comment]
*thumbs up*

**Pull request merged**
